# Generated by Django 5.1.2 on 2024-10-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_pdf', models.FileField(upload_to='project_pdfs/')),
                ('project_zip', models.FileField(upload_to='project_zips/')),
            ],
        ),
    ]
