# Generated by Django 5.1.2 on 2024-11-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_projectpurchase_order_id_projectpurchase_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
