# Generated by Django 5.1.1 on 2024-11-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_project_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('ML', 'ML'), ('Python', 'Python'), ('Django', 'Django'), ('PHP', 'PHP'), ('Azure', 'Azure')], max_length=20, null=True),
        ),
    ]
