# Generated by Django 5.1.1 on 2024-11-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('ML', 'ML'), ('Python', 'Python'), ('Django', 'Django'), ('PHP', 'PHP'), ('Azure', 'Azure'), ('AWS', 'AWS'), ('Flask', 'Flask'), ('React', 'React')], max_length=20, null=True),
        ),
    ]
