# Generated by Django 5.1.2 on 2024-11-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0008_contact_rename_message_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
