# Generated by Django 5.1.2 on 2024-11-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0011_contact_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
