# Generated by Django 5.1.2 on 2024-11-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0014_remove_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
