# Generated by Django 5.1.1 on 2025-06-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0017_alter_userprofile_mobile_number_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
    ]
