# Generated by Django 5.1.1 on 2025-06-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0020_project_created_at_alter_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Mini Project', 'Mini Project'), ('Major Project', 'Major Project')], max_length=20, null=True),
        ),
    ]
